name: Check Studio Flow
description: Offline validation of Studio Flow Definitions ([Documentation](https://github.com/zingdevlimited/studio-flow-actions/blob/v1/README.md#check))

inputs:
  CONFIG_PATH:
    required: true
    description: The path to the Studio Configuration file
  TOKEN:
    required: false
    description: "A GitHub token with `contents:read` permission (used if required files are not already checked out)"
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js