name: Sync Studio Flow
description: Download Studio Flow instances into source control

inputs:
  CONFIG_PATH:
    required: true
    description: The path to the Studio Configuration file
  TWILIO_API_KEY:
    required: true
    description: The Twilio Api Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio Api Secret
  TOKEN:
    required: false
    description: "A GitHub token with `contents:write` and `pullrequests:write` permissions"
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js